FROM --platform=linux/amd64 python:3.11.11-slim AS base
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared/ ./shared/

FROM base
COPY ingestion/ ./ingestion/
COPY config/    ./config/
COPY dataraw/   ./dataraw/
CMD ["python", "ingestion/dag.py"]
